version: '2'
services: 
    cluster.dns.server: 
        image: tumingjian/dnsmasq
        restart: always
        cap_add: 
         - NET_ADMIN
        ports: 
          - "53:53"
        volumes: 
          - /opt/soft/docker/env/dns-etc:/mnt/etc
        mem_limit: 128mb
        networks: 
          default: 
            ipv4_address: 172.18.0.250
        container_name: "cluster.dns.server"
    cluster.vpn.server:  
        image: hwdsl2/ipsec-vpn-server
        restart: always
        ports: 
          - "4500:4500/udp"
          - "500:500/udp"
        mem_limit: 128mb
        networks: 
          - default 
        volumes:  
          - /lib/modules:/lib/modules:ro
        env_file: 
          - /opt/soft/docker/env/vpn.env
        privileged: true
        container_name: "cluster.vpn.server"
networks: 
  default:
    external: 
      name: "docker-net"     
