version : '2'
services:
    cluster.namenode1.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd && bin/hdfs namenode -format -force && bin/hdfs namenode"
        volumes: 
           - /opt/soft/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        networks: 
           default: 
             ipv4_address: 172.18.0.231
        dns:
           - 172.18.0.250
        depends_on:
           - cluster.journalnode1.server
           - cluster.journalnode2.server
           - cluster.journalnode3.server
        container_name: cluster.namenode1.server
    cluster.namenode2.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd && bin/hdfs namenode -format -force && bin/hdfs namenode"
        volumes:
           - /opt/soft/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        networks:
           default:
             ipv4_address: 172.18.0.232
        dns:
           - 172.18.0.250
        depends_on:
           - cluster.journalnode1.server
           - cluster.journalnode2.server
           - cluster.journalnode3.server
        container_name: cluster.namenode2.server
    cluster.extramanager.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && /usr/sbin/sshd && /usr/local/hadoop/sbin/mr-jobhistory-daemon.sh start historyserver && /usr/local/hadoop/bin/yarn resourcemanager"
        volumes: 
           - /opt/soft/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
           - HADOOP_LIBEXEC_DIR=/usr/local/hadoop/libexec
           - HADOOP_MAPRED_HOME=/usr/local/hadoop
        working_dir: /usr/local/hadoop
        ports: 
           - "18088:18088"
           - "19888:19888"
        links: 
           - cluster.namenode1.server
           - cluster.namenode2.server
        networks: 
           default: 
             ipv4_address: 172.18.0.253
        dns:
           - 172.18.0.250
        container_name: cluster.extramanager.server
    cluster.journalnode1.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd && bin/hdfs journalnode"
        volumes:
           - /opt/soft/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        dns:
           - 172.18.0.250
        networks: 
           default: 
             ipv4_address: 172.18.0.241
        container_name: cluster.journalnode1.server
    cluster.journalnode2.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd && bin/hdfs journalnode"
        volumes: 
           - /opt/soft/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        dns:
           - 172.18.0.250
        networks: 
           default: 
             ipv4_address: 172.18.0.242
        container_name: cluster.journalnode2.server
    cluster.journalnode3.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd && bin/hdfs journalnode"
        volumes: 
           - /opt/soft/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        dns:
           - 172.18.0.250
        networks: 
           default: 
             ipv4_address: 172.18.0.243
        container_name: cluster.journalnode3.server
    cluster.datanode1.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd && /usr/local/hadoop/sbin/yarn-daemon.sh start nodemanager &&  bin/hdfs datanode"
        volumes:
          - /opt/soft/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        links: 
         - cluster.namenode1.server
         - cluster.namenode2.server
         - cluster.extramanager.server
        dns:
           - 172.18.0.250
        container_name: cluster.datanode1.server
        depends_on: 
           - cluster.namenode1.server
           - cluster.extramanager.server
    cluster.datanode2.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd && /usr/local/hadoop/sbin/yarn-daemon.sh start nodemanager && bin/hdfs datanode"
        volumes:
          - /opt/soft/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        links: 
           - cluster.namenode1.server
           - cluster.namenode2.server
           - cluster.extramanager.server
        dns:
           - 172.18.0.250
        container_name: cluster.datanode2.server
        depends_on: 
           - cluster.namenode1.server
           - cluster.extramanager.server
    cluster.datanode3.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd && /usr/local/hadoop/sbin/yarn-daemon.sh start nodemanager && bin/hdfs datanode"
        volumes:
          - /opt/soft/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        links: 
          - cluster.namenode1.server
          - cluster.namenode2.server
          - cluster.extramanager.server     
        dns:
           - 172.18.0.250
        container_name: cluster.datanode3.server
        depends_on: 
           - cluster.namenode1.server
           - cluster.extramanager.server
    cluster.datanode4.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd && /usr/local/hadoop/sbin/yarn-daemon.sh start nodemanager && bin/hdfs datanode"
        volumes:
          - /opt/soft/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        links:
          - cluster.namenode1.server
          - cluster.namenode2.server
          - cluster.extramanager.server
        dns:
           - 172.18.0.250
        container_name: cluster.datanode4.server
        depends_on:
           - cluster.namenode1.server
           - cluster.extramanager.server
networks: 
   default:
    external:
      name: "docker-net"

