version : '2'
services:
    cluster.namenode.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd && bin/hdfs namenode -format && bin/hdfs namenode"
        volumes: 
           - /Users/tumingjian/docker/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        ports:
           - "50090:50090"
           - "50070:50070"
           - "8808:8808"
           - "9000:9000"
           - "50030:50030"
        dns:
           - 172.19.0.250
        container_name: cluster.namenode.server
    cluster.datanode1.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd &&  bin/hdfs datanode"
        volumes:
          - /Users/tumingjian/docker/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        links: 
         - cluster.namenode.server
        dns:
           - 172.19.0.250
        container_name: cluster.datanode1.server
        depends_on: 
           - cluster.namenode.server
    cluster.datanode2.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd && bin/hdfs datanode"
        volumes:
          - /Users/tumingjian/docker/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        links: 
           - cluster.namenode.server
        dns:
           - 172.19.0.250
        container_name: cluster.datanode2.server
        depends_on: 
           - cluster.namenode.server
    cluster.datanode3.server:
        image: tumingjian/oracle-jdk
        restart: always
        command: sh -c "cp -R /mnt/hadoop-disk/* /usr/local/hadoop && ln -sf /usr/local/hadoop/sbin/* /usr/sbin/ && /usr/sbin/sshd && bin/hdfs datanode"
        volumes:
          - /Users/tumingjian/docker/hadoop-2.7.3:/mnt/hadoop-disk
        environment:
           - HADOOP_HOME=/usr/local/hadoop
           - HADOOP_CONF_DIR=/usr/local/hadoop/etc/hadoop
        working_dir: /usr/local/hadoop
        links: 
          - cluster.namenode.server     
        dns:
           - 172.19.0.250
        container_name: cluster.datanode3.server
        depends_on: 
           - cluster.namenode.server
networks: 
   default:
    external:
      name: "docker-net"

